### ISSUE TITLE
How is it supposed to be used?

### ISSUE THREAD

**Issue by gigix** [JirkaChadima/gitbook-plugin-link-checker#2]
It doesn't break "gitbook build", neither flush any error message, although I know there are links broken.

How is this plugin supposed to be used? Thanks!

**Comment by JirkaChadima** [comment]
Hi, you need to configure it in the `book.json` file. It is described in [README](https://github.com/JirkaChadima/gitbook-plugin-link-checker/blob/master/README.md). Without the configuration, gitbook doesn't run this plugin.
